# Code generated by layer version automation. DO NOT EDIT.

###########
# Datadog
###########

variable "datadog_extension_layer_version" {
  description = "Version for the Datadog Extension Layer"
  type        = number
  default     = 99
}

variable "datadog_dotnet_layer_version" {
  description = "Version for the Datadog .NET Layer"
  type        = number
  default     = 25
}

variable "datadog_java_layer_version" {
  description = "Version for the Datadog Java Layer"
  type        = number
  default     = 27
}

variable "datadog_node_layer_version" {
  description = "Version for the Datadog Node Layer"
  type        = number
  default     = 142
}

variable "datadog_python_layer_version" {
  description = "Version for the Datadog Python Layer"
  type        = number
  default     = 127
}

variable "datadog_ruby_layer_version" {
  description = "Version for the Datadog Ruby Layer"
  type        = number
  default     = 28
}

locals {
  runtime_catalog = {
    "dotnet6" = {
      runtime_family    = "dotnet"
      tracer_layer_name = "dd-trace-dotnet"
      tracer_layer_names = {
        x86_64 = "dd-trace-dotnet"
        arm64  = "dd-trace-dotnet-ARM"
      }
    }
    "dotnet7" = {
      runtime_family    = "dotnet"
      tracer_layer_name = "dd-trace-dotnet"
      tracer_layer_names = {
        x86_64 = "dd-trace-dotnet"
        arm64  = "dd-trace-dotnet-ARM"
      }
    }
    "dotnet8" = {
      runtime_family    = "dotnet"
      tracer_layer_name = "dd-trace-dotnet"
      tracer_layer_names = {
        x86_64 = "dd-trace-dotnet"
        arm64  = "dd-trace-dotnet-ARM"
      }
    }
    "dotnet10" = {
      runtime_family    = "dotnet"
      tracer_layer_name = "dd-trace-dotnet"
      tracer_layer_names = {
        x86_64 = "dd-trace-dotnet"
        arm64  = "dd-trace-dotnet-ARM"
      }
    }
    "java8.al2" = {
      runtime_family    = "java"
      tracer_layer_name = "dd-trace-java"
      tracer_layer_names = {
        x86_64 = "dd-trace-java"
        arm64  = "dd-trace-java"
      }
    }
    "java11" = {
      runtime_family    = "java"
      tracer_layer_name = "dd-trace-java"
      tracer_layer_names = {
        x86_64 = "dd-trace-java"
        arm64  = "dd-trace-java"
      }
    }
    "java17" = {
      runtime_family    = "java"
      tracer_layer_name = "dd-trace-java"
      tracer_layer_names = {
        x86_64 = "dd-trace-java"
        arm64  = "dd-trace-java"
      }
    }
    "java21" = {
      runtime_family    = "java"
      tracer_layer_name = "dd-trace-java"
      tracer_layer_names = {
        x86_64 = "dd-trace-java"
        arm64  = "dd-trace-java"
      }
    }
    "java25" = {
      runtime_family    = "java"
      tracer_layer_name = "dd-trace-java"
      tracer_layer_names = {
        x86_64 = "dd-trace-java"
        arm64  = "dd-trace-java"
      }
    }
    "nodejs18.x" = {
      runtime_family    = "nodejs"
      tracer_layer_name = "Datadog-Node18-x"
      tracer_layer_names = {
        x86_64 = "Datadog-Node18-x"
        arm64  = "Datadog-Node18-x"
      }
    }
    "nodejs20.x" = {
      runtime_family    = "nodejs"
      tracer_layer_name = "Datadog-Node20-x"
      tracer_layer_names = {
        x86_64 = "Datadog-Node20-x"
        arm64  = "Datadog-Node20-x"
      }
    }
    "nodejs22.x" = {
      runtime_family    = "nodejs"
      tracer_layer_name = "Datadog-Node22-x"
      tracer_layer_names = {
        x86_64 = "Datadog-Node22-x"
        arm64  = "Datadog-Node22-x"
      }
    }
    "nodejs24.x" = {
      runtime_family    = "nodejs"
      tracer_layer_name = "Datadog-Node24-x"
      tracer_layer_names = {
        x86_64 = "Datadog-Node24-x"
        arm64  = "Datadog-Node24-x"
      }
    }
    "python3.8" = {
      runtime_family    = "python"
      tracer_layer_name = "Datadog-Python38"
      tracer_layer_names = {
        x86_64 = "Datadog-Python38"
        arm64  = "Datadog-Python38-ARM"
      }
    }
    "python3.9" = {
      runtime_family    = "python"
      tracer_layer_name = "Datadog-Python39"
      tracer_layer_names = {
        x86_64 = "Datadog-Python39"
        arm64  = "Datadog-Python39-ARM"
      }
    }
    "python3.10" = {
      runtime_family    = "python"
      tracer_layer_name = "Datadog-Python310"
      tracer_layer_names = {
        x86_64 = "Datadog-Python310"
        arm64  = "Datadog-Python310-ARM"
      }
    }
    "python3.11" = {
      runtime_family    = "python"
      tracer_layer_name = "Datadog-Python311"
      tracer_layer_names = {
        x86_64 = "Datadog-Python311"
        arm64  = "Datadog-Python311-ARM"
      }
    }
    "python3.12" = {
      runtime_family    = "python"
      tracer_layer_name = "Datadog-Python312"
      tracer_layer_names = {
        x86_64 = "Datadog-Python312"
        arm64  = "Datadog-Python312-ARM"
      }
    }
    "python3.13" = {
      runtime_family    = "python"
      tracer_layer_name = "Datadog-Python313"
      tracer_layer_names = {
        x86_64 = "Datadog-Python313"
        arm64  = "Datadog-Python313-ARM"
      }
    }
    "python3.14" = {
      runtime_family    = "python"
      tracer_layer_name = "Datadog-Python314"
      tracer_layer_names = {
        x86_64 = "Datadog-Python314"
        arm64  = "Datadog-Python314-ARM"
      }
    }
    "provided.al2" = {
      runtime_family     = "provided"
      tracer_layer_name  = null
      tracer_layer_names = null
    }
    "provided.al2023" = {
      runtime_family     = "provided"
      tracer_layer_name  = null
      tracer_layer_names = null
    }
    "ruby3.2" = {
      runtime_family    = "ruby"
      tracer_layer_name = "Datadog-Ruby3-2"
      tracer_layer_names = {
        x86_64 = "Datadog-Ruby3-2"
        arm64  = "Datadog-Ruby3-2-ARM"
      }
    }
    "ruby3.3" = {
      runtime_family    = "ruby"
      tracer_layer_name = "Datadog-Ruby3-3"
      tracer_layer_names = {
        x86_64 = "Datadog-Ruby3-3"
        arm64  = "Datadog-Ruby3-3-ARM"
      }
    }
    "ruby3.4" = {
      runtime_family    = "ruby"
      tracer_layer_name = "Datadog-Ruby3-4"
      tracer_layer_names = {
        x86_64 = "Datadog-Ruby3-4"
        arm64  = "Datadog-Ruby3-4-ARM"
      }
    }
    "ruby4.0" = {
      runtime_family    = "ruby"
      tracer_layer_name = "Datadog-Ruby4-0"
      tracer_layer_names = {
        x86_64 = "Datadog-Ruby4-0"
        arm64  = "Datadog-Ruby4-0-ARM"
      }
    }
  }
}
