// Code generated by serverless-ci e2e-shared sync. DO NOT EDIT.
// Source of truth lives in serverless-ci/e2e/shared -- edit there; local changes are overwritten.

// Package e2eshared is the runner-agnostic toolkit shared by the serverless
// instrumentation e2e suites (Terraform modules, CDK, CFN macro, sls plugin),
// implementing the cross-cloud pieces of serverless-ci/e2e/spec.md.
//
// It imports nothing repo-specific: everything that varies is supplied through Config by
// a repo-local config file that is NOT part of this package. That keeps these files
// byte-identical across repos (vendored verbatim) and avoids an import cycle back into
// consumer code.
package e2eshared

const (
	// DefaultFreshnessTagKey holds a unix-seconds value the cross-repo sweeper ages
	// resources out by. Native creation time isn't usable cross-cloud, so we record it.
	DefaultFreshnessTagKey = "one_e2e_created"
	DefaultRunIDTagKey      = "one_e2e_run_id"
)

// Config parameterizes the shared helpers for one delivery tool + platform. A repo-local
// (non-synced) config builds this and passes it into the shared funcs.
type Config struct {
	Tool     string
	Platform string
	// Command is the CLI binary Run/RunWithRetries invoke, e.g. "aws", "az".
	Command string
	// RetryPatterns are transient cloud-error substrings safe to retry. Anything else is
	// a real failure, surfaced immediately.
	RetryPatterns []string
	// NameMaxLen caps ResourceName length (some platforms have tight budgets); 0 = no cap.
	NameMaxLen int
	// Env holds extra "KEY=VALUE" entries appended to os.Environ() for every command.
	Env []string
	// FreshnessTagKey / RunIDTagKey override the defaults above when non-empty.
	FreshnessTagKey string
	RunIDTagKey     string
}

func (c Config) freshnessTagKey() string {
	if c.FreshnessTagKey != "" {
		return c.FreshnessTagKey
	}

	return DefaultFreshnessTagKey
}

func (c Config) runIDTagKey() string {
	if c.RunIDTagKey != "" {
		return c.RunIDTagKey
	}

	return DefaultRunIDTagKey
}
