// Code generated by serverless-ci e2e-shared sync. DO NOT EDIT.
// Source of truth lives in serverless-ci/e2e/shared -- edit there; local changes are overwritten.

package e2eshared

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

type Result struct {
	ExitCode int
	Stdout   string
	Stderr   string
}

func (c Config) isRetryable(r Result) bool {
	out := r.Stdout + " " + r.Stderr
	for _, p := range c.RetryPatterns {
		if strings.Contains(out, p) {
			return true
		}
	}

	return false
}

// Run executes cfg.Command once with the given args. It returns the Result and a
// non-nil error when the command exits non-zero (inspect Result for output either way).
func Run(ctx context.Context, cfg Config, args ...string) (Result, error) {
	cmd := exec.CommandContext(ctx, cfg.Command, args...)
	if len(cfg.Env) > 0 {
		cmd.Env = append(os.Environ(), cfg.Env...)
	}
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()

	res := Result{Stdout: strings.TrimSpace(stdout.String()), Stderr: strings.TrimSpace(stderr.String())}
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			res.ExitCode = exitErr.ExitCode()
		} else {
			res.ExitCode = 1
			if res.Stderr == "" {
				res.Stderr = err.Error()
			}
		}

		return res, fmt.Errorf("%s %s failed (exit %d): %s", cfg.Command, strings.Join(args, " "), res.ExitCode, res.Stderr)
	}

	return res, nil
}

// RunWithRetries runs cfg.Command, retrying only on transient errors (matched against
// cfg.RetryPatterns) up to maxAttempts, sleeping delay between attempts. It retries the
// cloud, never past a real failure: a non-retryable error surfaces immediately.
func RunWithRetries(ctx context.Context, cfg Config, maxAttempts int, delay time.Duration, args ...string) (Result, error) {
	if maxAttempts < 1 {
		maxAttempts = 1
	}
	var res Result
	var err error
	for attempt := 1; attempt <= maxAttempts; attempt++ {
		res, err = Run(ctx, cfg, args...)
		if err == nil {
			return res, nil
		}
		if attempt < maxAttempts && cfg.isRetryable(res) {
			select {
			case <-ctx.Done():
				return res, ctx.Err()
			case <-time.After(delay):
			}

			continue
		}

		return res, err
	}

	return res, err
}
