// Code generated by serverless-ci e2e-shared sync. DO NOT EDIT.
// Source of truth lives in serverless-ci/e2e/shared -- edit there; local changes are overwritten.

package e2eshared

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

// NamePrefix is the sweeper's blast-radius guard: one-e2e-<tool>-<platform>. "one" is
// the team marker (dd- implied). Set atomically at creation, it is both the identity
// and the prefix the cross-repo sweeper keys on.
func (c Config) NamePrefix() string {
	return fmt.Sprintf("one-e2e-%s-%s", c.Tool, c.Platform)
}

// NewRunID returns an 8-char hex run id.
func NewRunID() string {
	b := make([]byte, 4)
	if _, err := rand.Read(b); err != nil {
		panic(fmt.Sprintf("e2eshared: cannot read random bytes: %v", err))
	}

	return hex.EncodeToString(b)
}

// ResourceName returns the run-scoped resource name "<prefix>-<runID>", truncated to
// cfg.NameMaxLen when that is set (some platforms have tight name budgets).
func ResourceName(cfg Config, runID string) string {
	name := cfg.NamePrefix() + "-" + runID
	if cfg.NameMaxLen > 0 && len(name) > cfg.NameMaxLen {
		name = name[:cfg.NameMaxLen]
	}

	return name
}

// Tags returns the hygiene tags stamped on every created resource: the freshness tag
// (unix seconds) and the run-id marker. createdUnix is supplied by the caller so the
// value is captured atomically at create time.
func Tags(cfg Config, runID string, createdUnix int64) map[string]string {
	return map[string]string{
		cfg.freshnessTagKey(): fmt.Sprintf("%d", createdUnix),
		cfg.runIDTagKey():     runID,
	}
}
