// Code generated by serverless-ci e2e-shared sync. DO NOT EDIT.
// Source of truth lives in serverless-ci/e2e/shared -- edit there; local changes are overwritten.

package e2eshared

import (
	"context"
	"crypto/tls"
	"net/http"
	"time"
)

// GenerateTraffic issues GET requests to url every interval until ctx is cancelled, so a
// serverless-init sidecar tailing a log file from the end always has fresh lines to
// forward while telemetry is polled. Best-effort: request errors are ignored.
func GenerateTraffic(ctx context.Context, url string, interval time.Duration) {
	client := &http.Client{
		Timeout:   30 * time.Second,
		Transport: &http.Transport{TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS12}},
	}

	hit := func() {
		if resp, err := client.Get(url); err == nil {
			resp.Body.Close()
		}
	}

	hit() // start producing immediately, don't wait a full interval

	t := time.NewTicker(interval)
	defer t.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-t.C:
			hit()
		}
	}
}
