// Code generated by serverless-ci e2e-shared sync. DO NOT EDIT.
// Source of truth lives in serverless-ci/e2e/shared -- edit there; local changes are overwritten.

package e2eshared

import (
	"fmt"
	"sort"
	"strings"
)

// Violations accumulates contract-violation messages so a verifier can report every
// mismatch at once rather than failing on the first. It is runner-agnostic: callers
// turn the accumulated result into a test failure however they like.
type Violations struct {
	msgs []string
}

func (v *Violations) Addf(format string, args ...any) {
	v.msgs = append(v.msgs, fmt.Sprintf(format, args...))
}

func (v *Violations) Any() bool { return len(v.msgs) > 0 }

// Err returns nil when clean, else an error listing every violation under context.
func (v *Violations) Err(context string) error {
	if len(v.msgs) == 0 {
		return nil
	}

	return fmt.Errorf("%s:\n  - %s", context, strings.Join(v.msgs, "\n  - "))
}

// RequireValues asserts every want[k] is present in got with the exact value (identity,
// not existence). label names the map (e.g. "env var", "tag") in violation messages.
func RequireValues(v *Violations, label string, got map[string]string, want map[string]string) {
	for _, k := range sortedKeys(want) {
		switch g, ok := got[k]; {
		case !ok:
			v.Addf("missing %s %s", label, k)
		case g != want[k]:
			v.Addf("%s %s = %q, want %q", label, k, g, want[k])
		}
	}
}

// RequirePresent asserts each key is present and non-empty in got (value not checked).
func RequirePresent(v *Violations, label string, got map[string]string, keys ...string) {
	for _, k := range keys {
		if got[k] == "" {
			v.Addf("missing %s %s", label, k)
		}
	}
}

// ForbidKeyPrefix records a violation for every key in got starting with prefix. Used to
// assert the uninstrumented end-state (e.g. no residual DD_* env vars after remove).
func ForbidKeyPrefix(v *Violations, label string, got map[string]string, prefix string) {
	for _, k := range sortedKeys(got) {
		if strings.HasPrefix(k, prefix) {
			v.Addf("residual %s %s", label, k)
		}
	}
}

// RequireHygieneTags asserts the resource carries the run-id marker and freshness tag
// stamped at creation (see ResourceName/Tags), keyed per cfg.
func RequireHygieneTags(v *Violations, cfg Config, tags map[string]string, runID string) {
	if got := tags[cfg.runIDTagKey()]; got != runID {
		v.Addf("%s tag = %q, want %q", cfg.runIDTagKey(), got, runID)
	}
	if tags[cfg.freshnessTagKey()] == "" {
		v.Addf("missing %s freshness tag", cfg.freshnessTagKey())
	}
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	return keys
}
